echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "We are learning AWS, Azure DevOps and DevSecOps"
echo "I am learning in batch-29"
echo "My name is Anil Yadav and i am learning DevOps and Middleware"
echo "I will do my best to fite in this roles"
echo "I have to start my career in DevOps"
echo "New branch created"
